# docker-compose.yml

version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres # Replace with your PostgreSQL username
      POSTGRES_PASSWORD: password # Replace with your PostgreSQL password
      POSTGRES_DB: quizz # Replace with your PostgreSQL database name
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: